### ISSUE TITLE
ClassicUA + Questie = Broken Quest Dialog

### ISSUE THREAD

**Issue by frizar** [greenya/ClassicUA#20]
неможливо відкрити квест, коли нажимаеш на нього. не видно тексту (вітання). скрін не можу кинути, бо я вже відключив квесті і взяв той квест. потім включив знову. тепер просто немає тексту (вітання), але відкрити його я вже можу. десь ці 2 аддони заважають одне одному.

ClassicUA + Questie:
<img width="853" alt="image" src="https://github.com/greenya/ClassicUA/assets/8735701/ef214d00-2abf-431b-8a3e-553510d4957f">

ClassicUA only:
<img width="817" alt="image" src="https://github.com/greenya/ClassicUA/assets/8735701/14d9be57-44ef-421a-9617-b5cdc348a181">

**Comment by greenya** [comment]
Якась дрібна помилка в Questie. Достатньо відключити всі аддони, окрім Questie, і помилка буде повторюватися (в незалежності чи ClassicUA ввімкнено). "Дрібна", бо виглядає так що щоб ця помилка відбулася, потрібно не дати Questie повністю завантажитися, тобто послі `/reload` одразу швидко почати розмову з цим нпц, тоді буде помилка. Якщо ж почекати 5-6 сек, коли Questie відобразить свій трекер квестів, то помилка не відбувається.

Ось скріншот з відображенням деталей lua помилок, видно де саме (файл, рядок) помилка
![image](https://github.com/greenya/ClassicUA/assets/1086543/7de8b604-a99f-4118-9609-158001c57027)
