### ISSUE TITLE
spells with and witout parameters

### ISSUE THREAD

**Issue by DanyloMeranov** [greenya/ClassicUA#22]
зустрічаються описи вмінь, де замість числових значень показані параметри
![image](https://github.com/greenya/ClassicUA/assets/130688213/6acfba66-85c7-43d2-9547-833981031cab)
це на Classic Era 1.14.4

**Comment by DanyloMeranov** [comment]
також дуже багато описів зі сталими цифрами, що не співпадають з оригінальним підписом
![image](https://github.com/greenya/ClassicUA/assets/130688213/94f5c70e-4065-400a-ae14-910be74fe381)

**Comment by greenya** [comment]
Це відома проблема і вона в процесі виправлення. Всі класові закляття, таланти і їх аури (бафи/дебафи) переглядаються, частково перефразовуються і виправляються. Наразі це зроблено для всіх класів окрім паладина, чорнокнижника та мисливця -- ці зміни будуть в наступній версії аддону.

**Comment by DanyloMeranov** [comment]
> Це відома проблема і вона в процесі виправлення. Всі класові закляття, таланти і їх аури (бафи/дебафи) переглядаються, частково перефразовуються і виправляються. Наразі це зроблено для всіх класів окрім паладина, чорнокнижника та мисливця -- ці зміни будуть в наступній версії аддону.

Дякую!
