### ISSUE TITLE
Помилки в описі рун воїна

### ISSUE THREAD

**Issue by Wilford1990** [greenya/ClassicUA#38]
Доброго дня! Слава Україні!

Знайшов наступні помилки в описі рун воїна (скріни у вкладенні):
1. Devastate (Спустошення) - невірний опис від іншої руни "Нескінченна лють";
2. Furious Thunder (Несамовитий грім) - невірний опис від іншої руни "Цілеспрямована лють". Також побачив, що сам опис руни "Цілеспрямована лють" містить у собі помилку: "Коли ви тримаєте зброю у кожній руці, ваша шкода та швидкість руху збільшується на {1}%".

Величезне дякую Вам за даний проєкт, дуже приємно грати в улюблену гру рідною мовою :)
![WoWScrnShot_010524_110608](https://github.com/greenya/ClassicUA/assets/155723803/7ee14176-4cb9-4dac-b469-10fcfe0a9075)
![WoWScrnShot_010524_110558](https://github.com/greenya/ClassicUA/assets/155723803/e738a9eb-b1ca-42ed-ad26-6f01004adcd3)

**Comment by greenya** [comment]
Вітаю. Героям слава!

Дякую за репорт, ці 2 руни, а також інші у воїна були виправлені. Помилка була в невірних посиланнях на закляття. Також, помилка з відображенням "{1}%" має виправиться автоматично.

Ці зміни будуть помітні в наступній версії аддону.

**Comment by Wilford1990** [comment]
> Вітаю. Героям слава!
> 
> Дякую за репорт, ці 2 руни, а також інші у воїна були виправлені. Помилка була в невірних посиланнях на закляття. Також, помилка з відображенням "{1}%" має виправиться автоматично.
> 
> Ці зміни будуть помітні в наступній версії аддону.

Гарно дякую за відклик та Вашу Величезну роботу.
