### ISSUE TITLE
Невеличкі механічні помилки у текстах перекладів квестів (низький пріоритет)

### ISSUE THREAD

**Issue by Wilford1990** [greenya/ClassicUA#41]
Доброго дня! Слава Україні!

Повідомляю про знайдені мною невеличкі механічні помилки у текстах перекладів квестів:

![WoWScrnShot_011124_121932](https://github.com/greenya/ClassicUA/assets/155723803/5d6a4b10-65f1-4f33-9d0b-77ed5d9cd71c)
![WoWScrnShot_011124_130415](https://github.com/greenya/ClassicUA/assets/155723803/8d4e1276-68c1-4b24-a653-4fe4e30cc00f)
![WoWScrnShot_010824_092621](https://github.com/greenya/ClassicUA/assets/155723803/1d072eb2-a5ac-4e0f-b112-3f910b271a58)

Величезне дякую Вам за колосальну роботу.

**Comment by Jakanis** [comment]
@Wilford1990 Буде виправлено в наступній версії
Дуже дякую за допомогу ❤️

**Comment by greenya** [comment]
Дякую за репорт автору та за швидке реагування @Jakanis :)
Закриваю цей issue.
