### ISSUE TITLE
Нові невеличкі механічні помилки у текстах перекладів квестів та створінь (станом на 29.01.2024)

### ISSUE THREAD

**Issue by Wilford1990** [greenya/ClassicUA#48]
Доброго дня! Слава Україні!

Повідомляю про знайдені мною невеличкі механічні помилки у текстах перекладів квестів та створінь станом на 29.01.2024:

![WoWScrnShot_012224_194538](https://github.com/greenya/ClassicUA/assets/155723803/a3bf94b1-2950-4edb-82f4-68f02cf94e90)
![WoWScrnShot_012324_123114](https://github.com/greenya/ClassicUA/assets/155723803/dcf2173f-d37e-4701-bcbe-4a868fe0f84c)
![WoWScrnShot_012324_130023](https://github.com/greenya/ClassicUA/assets/155723803/9decf94f-4a36-4ca0-a336-1d3b056be653)
![WoWScrnShot_012324_171154](https://github.com/greenya/ClassicUA/assets/155723803/b6d6df9d-e9d7-49fa-a13b-df4c07b230e7)
![WoWScrnShot_012324_185243](https://github.com/greenya/ClassicUA/assets/155723803/1f4128c0-d743-4679-963d-27fd3068d602)
![WoWScrnShot_012324_185853](https://github.com/greenya/ClassicUA/assets/155723803/643ebc6e-52ea-4cfd-8f40-aabedadd8507)
![WoWScrnShot_012324_190114](https://github.com/greenya/ClassicUA/assets/155723803/435dbd02-52b4-48f4-8d5f-9543c18dbe1f)
![WoWScrnShot_012324_190550](https://github.com/greenya/ClassicUA/assets/155723803/a1b5db40-2762-4e73-be24-6f7e260e6be3)
![WoWScrnShot_012424_145947](https://github.com/greenya/ClassicUA/assets/155723803/c212aa70-404c-453f-8263-d71182f3e2ea)
![WoWScrnShot_012424_165348](https://github.com/greenya/ClassicUA/assets/155723803/00d873b3-4d4c-430f-bd1e-aee1f0334b2e)
![WoWScrnShot_012524_183849](https://github.com/greenya/ClassicUA/assets/155723803/63880dea-a334-49cd-ac62-1eff51b90dc8)
![WoWScrnShot_012624_133823](https://github.com/greenya/ClassicUA/assets/155723803/3a5c96f0-b626-4c3b-9488-9e40ad9ee655)
![WoWScrnShot_012624_161804](https://github.com/greenya/ClassicUA/assets/155723803/1da5c806-d918-42c5-9d72-3878719e5d7d)
![WoWScrnShot_012624_161830](https://github.com/greenya/ClassicUA/assets/155723803/46637cb6-f142-42ff-ba54-2188eb7f44f9)
![WoWScrnShot_012824_005224](https://github.com/greenya/ClassicUA/assets/155723803/3725756b-a8cc-4154-a36b-f63eb95080cf)
![WoWScrnShot_012824_011519](https://github.com/greenya/ClassicUA/assets/155723803/87803762-4972-4650-96b1-3c24c83feb3a)

Величезне дякую Вам за колосальну роботу.

**Comment by greenya** [comment]
Дякую за репорт 🍻, виправимо.

**Comment by greenya** [comment]
@Wilford1990 до речі, спробуй додати аддон [Leatrix Plus](https://www.curseforge.com/wow/addons/leatrix-plus-classic), там є зручна опція для збільшення висоти списку завдань вікна Quest Log, буде список не із 6 завдань, а повна висота, справа опис вибраного завдання на всю висоту, при цьому ClassicUA все нормально відображає (підлаштовується під позицію та висоту секції з оригінальним описом).

**Comment by Wilford1990** [comment]
> @Wilford1990 до речі, спробуй додати аддон [Leatrix Plus](https://www.curseforge.com/wow/addons/leatrix-plus-classic), там є зручна опція для збільшення висоти списку завдань вікна Quest Log, буде список не із 6 завдань, а повна висота, справа опис вибраного завдання на всю висоту, при цьому ClassicUA все нормально відображає (підлаштовується під позицію та висоту секції з оригінальним описом).

Дякую за пораду, обов’язково спробую :)

**Comment by Jakanis** [comment]
Дякую, виправив на Crowdin
Окрім деяких пунктів:
10) tracker - залишив пантрувачем, бо слідопитами вже називаються ranger (вищі ельфи) та pathfinder (хутропузи, свинобрази, тощо)
12) Залишив дріаду ввічливою, як і її сестру, що дає це завдання. Хоча в цьому пункті не впевнений, але ж дріади ніби саме в такому тоні в інших завданнях звертаються до гравців.
