### ISSUE TITLE
Критична помилка клієнта з послідуючим зависанням через аддон Classic UA (Високий пріоритет!)

### ISSUE THREAD

**Issue by Wilford1990** [greenya/ClassicUA#50]
Доброго дня! Слава Україні!

Аддон розпочав викликати критичну помилку клієнта при наведенні миші на рецепт Plans: Mantle of the Second War (item=210779) у продавця Marcy Baker <Supply Officer> фракції Azeroth Commerce Authority у Дарнасі. Підозрюю, що проблема виникатиме у всіх продавців даної фракції у всіх столицях.

Попереджуючи Ваше запитання, чи проблема саме у аддоні Classic UA, повідомляю, що під час тестування були вимкнуті усі аддони і методом підбору було визначено, що помилку спричиняє саме аддон Classic UA.

Error ID: 664AFE15-C56B-477C-9F09-50B857544B40

![1 — копия](https://github.com/greenya/ClassicUA/assets/155723803/90079c15-57ab-4dcb-852f-c56d65c829bd)
![2 — копия](https://github.com/greenya/ClassicUA/assets/155723803/8f73ff0f-631c-43ce-b436-d53d34174b8f)
![1 — копия (2)](https://github.com/greenya/ClassicUA/assets/155723803/3ad8f942-b37b-4f69-af9e-09033c03aa41)

Величезне дякую Вам за колосальну роботу.

**Comment by greenya** [comment]
Дякую за репорт. Вже знайшов проблему, їх по суті дві:

![image](https://github.com/greenya/ClassicUA/assets/1086543/813e8db6-10d1-40a3-b652-666fcb539812)
- додали предмет-рецепт помилково з посиланням на результуючий предмет на самого себе
- в коді ця ситуація не була передбачена й не було перевірки

Буде виправлено.
