### ISSUE TITLE
Нові невеличкі механічні помилки у текстах перекладів квестів та створінь (станом на 05.02.2024)

### ISSUE THREAD

**Issue by Wilford1990** [greenya/ClassicUA#52]
Доброго дня! Слава Україні!

Повідомляю про знайдені мною невеличкі механічні помилки у текстах перекладів квестів та створінь станом на 05.02.2024:

![WoWScrnShot_020224_114225](https://github.com/greenya/ClassicUA/assets/155723803/238cad8c-b107-468f-b89b-449e990baaee)
![WoWScrnShot_020224_121132](https://github.com/greenya/ClassicUA/assets/155723803/fb0e9e97-2d5a-43df-873d-bc50951c1d3d)
![WoWScrnShot_020224_121552](https://github.com/greenya/ClassicUA/assets/155723803/25e8c7dd-17c5-4926-9f38-c7e031785f0c)
![WoWScrnShot_020324_001201](https://github.com/greenya/ClassicUA/assets/155723803/e516d58f-857d-42f0-a0bf-db1b97eb0808)
![WoWScrnShot_020324_001305](https://github.com/greenya/ClassicUA/assets/155723803/8e964609-5d70-42a5-ba15-6c8d372b0c17)
![WoWScrnShot_020224_150044](https://github.com/greenya/ClassicUA/assets/155723803/eff14aa3-c897-4b27-9472-ed3cec0758ff)
![WoWScrnShot_020224_150520](https://github.com/greenya/ClassicUA/assets/155723803/2d0c6bf5-7583-46d6-a98c-50ae74a8fd3d)
![WoWScrnShot_020224_152108](https://github.com/greenya/ClassicUA/assets/155723803/6a6ecf96-d2de-49c4-9ec6-23650427b8ee)
![WoWScrnShot_020324_001151](https://github.com/greenya/ClassicUA/assets/155723803/8ac5c8f9-c7c9-4abd-b01f-657e8eb82f58)
![WoWScrnShot_020324_001337](https://github.com/greenya/ClassicUA/assets/155723803/19b136ff-6d1f-4a8b-90ce-f086bf3749d7)
![WoWScrnShot_020524_013348](https://github.com/greenya/ClassicUA/assets/155723803/0df32d12-e8fb-4bee-8dc0-09bebc66ca27)

Також в усіх Предків Місячного фестивалю була знайдена невеличка помилка з комами:

![WoWScrnShot_020524_100855](https://github.com/greenya/ClassicUA/assets/155723803/f82930f8-2962-455e-bb22-bc06c31847cb)

Величезне дякую Вам за колосальну роботу.

**Comment by greenya** [comment]
Дякую за репорт 🍻

**Comment by Jakanis** [comment]
Щиро дякую за репорт. Особливо за книги - їх зазвичай ніхто й не читає :)
Виправив на Crowdin
