### ISSUE TITLE
Не співпадають цифрові значення в підписах для Season of Discovery

### ISSUE THREAD

**Issue by DanyloMeranov** [greenya/ClassicUA#56]
Велика кількість айтемів із доповнення Season of Discovery мають відмінності в цифрових значеннях оригіналу і перекладу.
Як приклад:
![image](https://github.com/greenya/ClassicUA/assets/130688213/bdce078a-f365-43f0-aa9c-84f5f264ae8a)

**Comment by greenya** [comment]
Дякую за репорт 🤝 
Скоро виправимо.

**Comment by greenya** [comment]
Цей предмет та багато інших були виправлені в останній (5.5) версії. Якщо бачите ще якісь неточності з іншими предметами, будь ласка, створюйте нову тему (issue).
